### PR TITLE
Update page title to align with left nav title

### PR DESCRIPTION
**Pull request by Nashaath**
## Purpose
Update page title to align with left nav title.

### CODE REVIEW

**Comment by anupama-pathirage** [comment]
@Nashaath Shall we rename the file names also with the same topic. Otherwise, when they are not in-sync will be very hard to manage and remember in the future. Please fix the navigations also when the file name gets changed.

**Comment by Nashaath** [comment]
+1. We need to follow that best practice.

**Comment by Nashaath** [comment]
Renamed `root-cause-analysis.md` to `perform-root-cause-analysis.md`.
Updated the nav via https://github.com/wso2/docs-choreo-dev/pull/57 to reflect this change

**Review by RukshiW — APPROVED** [review]

**Comment by Nashaath** [comment]
Closed #57 and added the relevant commits here.

**Review by anupama-pathirage — APPROVED** [review]

**Pull request merged**
