### PR TITLE
Move navigation to the bottom of the page & improve breadcrumbs

### PR DESCRIPTION
**Pull request by anupama-pathirage**
## Purpose
Fixes https://github.com/wso2-enterprise/choreo/issues/3817

Screen-Recording-2021-05-30-at-1

### CODE REVIEW

**Comment by shaniR** [comment]
Do we really need this feature? I think we should remove this and introduce a "related links" list to the end of the page to increase internal links that will help SEO.

**Comment by anupama-pathirage** [comment]
I too suggested to remove this  feature in the mail thread [1] due to the following reason:
` It consumes a lot of space at the top and then it looks like the page is not compact enough so that users can't grab the most without scrolling. Normally the users won't follow this site step by step as these are bit unrelated topics and the main source of traffic is via console to different pages. Also if needed, left navigation is enough to give the idea of what is next. `

Here I have moved it to bottom as @Nashaath suggested to move that to the bottom in [2]. @Nashaath Any specific reason to keep it?

[1] Re: Choreo Documentation Site
[2] https://github.com/wso2-enterprise/choreo/issues/3817

**Comment by Nashaath** [comment]
I mentioned in the mail thread that I'm +1 to remove. I recall bringing this up when the site was initially done and at that time we decided to just leave it, so wasn't sure whether all were +1 to remove.

**Comment by anupama-pathirage** [comment]
> I mentioned in the mail thread that I'm +1 to remove. I recall bringing this up when the site was initially done and at that time we decided to just leave it, so wasn't sure whether all were +1 to remove.

Then shall we keep this at the bottom for now until we do the related links suggestions in the future? @shaniR , @Nashaath wdht?

**Review by shaniR — APPROVED** [review]

**Pull request merged**
