### PR TITLE
Fix image width

### PR DESCRIPTION
**Pull request by shaniR**
Fixes https://github.com/wso2-enterprise/choreo/issues/3806

### CODE REVIEW

**Comment by anupama-pathirage** [comment]
@shaniR There are images with same issue in other pages as well. Please fix them all in this PR as same change will apply for all.

**Comment by shaniR** [comment]
@RukshiW  we can close this off right? Did you do this change and the rest of the image changes as well?

**Comment by RukshiW** [comment]
The correction done via the extension was only applied to one image.

**Comment by anupama-pathirage** [comment]
Closing this as the fix for all the images is sent via https://github.com/wso2/docs-choreo-dev/pull/100

**Pull request closed without merging**
