### PR TITLE
Use concise statements

### PR DESCRIPTION
**Pull request by RukshiW**

### CODE REVIEW

**Comment by anupama-pathirage** [comment]
It seems this fixes the issue https://github.com/wso2-enterprise/choreo/issues/3837 So please mention this in the description with proper key words to make sure issue is getting closed automatically with the PR merge. Refer point 5 in [1]


Also fix rthe same in [2] too
[1] https://github.com/wso2-enterprise/choreo#submit-your-contribution
[2] https://github.com/wso2/docs-choreo-dev/blob/main/en/docs/integrations/integration-concepts.md

**Comment by RukshiW** [comment]
Resolves wso2-enterprise/choreo#3837

**Comment by anupama-pathirage** [comment]
It seems the same changes are  sent in https://github.com/wso2/docs-choreo-dev/pull/71/files too. So shall we close this?

**Comment by RukshiW** [comment]
The changes are already covered in #71

**Pull request closed without merging**
